// Kentucky Bluegrass Lawn — Poa pratensis
// Edit this file to update plant-specific content.

#import "../../template.typ": *
#import "../generated/plant_data.typ": plant-established, plant-lifespan, plant-tier, plant-failure

#plant-header("Kentucky Bluegrass Lawn", "Poa pratensis", "bluegrass", establishment: plant-established("bluegrass"), lifespan: plant-lifespan("bluegrass"), tier: plant-tier("bluegrass"), failure: plant-failure("bluegrass"))[
 Kentucky Bluegrass is by far the most common lawn grass in Colorado and is well adapted to the Front Range climate when properly managed. A cool-season grass, it grows actively in spring and fall when temperatures are 60–75°F and may enter summer semi-dormancy during July–August heat. Your soil test reveals several important factors specific to your lawn: LOW nitrogen (the most limiting nutrient for turf), HIGH phosphorus (meaning starter fertilizer during sod installation has already provided lasting P; do not add more), LOW potassium (critical for winter hardiness and drought tolerance), and very low micronutrients. Mowing height note: CSU Extension's research-based recommendation for all Colorado lawns is 2.5–3 inches year-round — this specific height is climate-justified for Commerce City.
]

=== Watering

On a sprinkler system. Target 1.0–1.5 inches of water per week in June–August, applied in 2–3 cycles (to avoid runoff). Water deeply and infrequently rather than shallowly and daily — this develops deeper roots. In Commerce City's semi-arid climate with intense UV and low humidity, Kentucky Bluegrass may need more water than national average recommendations suggest. Water at dawn (5–7am) to reduce disease pressure and evaporation. In spring (May) and fall (September–October), 0.5–0.75 inches per week is sufficient. Run a catch test annually: place empty tuna cans in the lawn and time how long it takes to collect 1 inch — this calibrates your system's actual output to the recommended amount.

=== Fertilization

Per soil profile, use zero-phosphorus fertilizers and run a fall-weighted five-pass program in the audited annual range (~2.5–3.25 lb N/1,000 sq ft): early May granular ammonium sulfate (0.75–1.0 lb N), mid-June ammonium sulfate (0.5 lb N), early September liquid 28-0-0 (~0.5 lb N), late September liquid 28-0-0 + liquid 0-0-25 K (~0.5 lb N), and late October winterizer (~0.5 lb N). If either September liquid pass is missed, switch immediately to slow-release granular urea fallback at 1.0–1.25 lb N. Apply the spring chelated micronutrient blend as the annual micronutrient correction.

=== Pruning & Maintenance

Mowing height and frequency are the most critical turf management practices in Colorado. MOWING HEIGHT: Set your mower to 2.5–3 inches and maintain this height year-round. CSU Extension research for Colorado specifically demonstrates that this height maximizes drought and heat tolerance by shading the soil surface (reducing evaporation and soil temperature), encouraging deeper root growth, reducing photosynthesis loss during heat stress, and outcompeting weeds. Cutting shorter than 2 inches significantly increases water demand, weed pressure, and heat stress in Commerce City's semi-arid climate. Do NOT lower the mowing height in fall 'to scalp for winter.' MOWING FREQUENCY: Mow frequently enough to remove no more than 1/3 of the blade at each cutting — every 4–7 days during spring peak growth, every 7–14 days in summer. CLIPPINGS: Leave clippings on the lawn — they return approximately 0.5 lb nitrogen per 1,000 sq ft per year and do not cause thatch. Always mow with sharp blades.

=== Wildlife Value

Kentucky Bluegrass lawn provides limited direct wildlife value but does support the broader garden ecosystem. American robins and European collared doves forage the lawn surface for earthworms and grubs. House finches occasionally pick at grass seeds in sparse areas. The open lawn area is foraging territory for red-wing blackbirds and starlings, which probe for surface insects. Northern flickers are ground-foraging woodpeckers that dig in lawns for ants and beetle larvae — seeing one on your lawn is normal and welcome. Cottontail rabbits commonly graze lawn areas, especially at edges. Field mice can burrow at lawn edges near mulch beds — see pest management. A well-maintained lawn with minimal pesticide use supports the beneficial insect and earthworm populations that feed this bird community.

=== Pests & Disease

MOWING HEIGHT IS YOUR BEST DISEASE PREVENTION: In Colorado's semi-arid climate, #link("https://www.google.com/search?q=Kentucky+bluegrass+lawn+diseases+Colorado")[lawn diseases] are significantly less prevalent than in humid regions. Cultural practices (mowing height, watering timing, aeration) prevent 80% of common issues. #link("https://www.google.com/search?q=necrotic+ring+spot+Colorado+bluegrass+treatment")[Necrotic ring spot] appears as rings of dead grass with green centers in June–July; core aerate, deep water, reduce N fertility. #link("https://www.google.com/search?q=leaf+spot+Kentucky+bluegrass+treatment")[Leaf spot and melting out] causes tan spots on blades in late spring — improve drainage, reduce N applications. #link("https://www.google.com/search?q=bluegrass+spider+mites+treatment")[Bluegrass spider mites] are a drought-stress amplifier; lawn areas with red-brown color following dry periods may be mite-damaged — water deeply and consistently to reduce mite pressure. #link("https://www.google.com/search?q=lawn+grubs+Colorado+treatment")[Grubs] (beetle larvae) cause dead patches that pull up easily; apply milky spore or parasitic nematodes in late summer. Field mice burrow at lawn-to-mulch-bed edges — maintain a 4–6" mulch-free clear zone around the lawn perimeter where it meets planting beds.

=== Other Care

AERATION: Core aeration is the most impactful annual maintenance task for your lawn in clay soil. Aerate annually in late August–September, removing 3-inch deep cores to improve oxygen penetration and water infiltration. Overseed thin spots in early September directly after aerating. GYPSUM: Not recommended for this soil. Gypsum works by displacing sodium from clay exchange sites (sodic soils), but this soil is calcium-dominated, not sodium-dominated — the mechanism has nothing to act on here. Skip gypsum until a soil test confirms elevated sodium or high exchangeable sodium percentage (ESP).DETHATCHING: Dethatch in late summer if the thatch layer exceeds 1/2 inch — use a power rake or vertical mower. Thatch above 1/2 inch causes shallow rooting and magnifies drought stress. PRE-EMERGENT: Apply pre-emergent herbicide (prodiamine or pendimethalin) mid-April (when forsythia blooms) to suppress crabgrass and other annual weeds. Do not apply pre-emergent if you plan to overseed — wait 8–12 weeks after overseeding to use pre-emergents.
