#!/usr/bin/env python3
"""Generate Typst plant data include from data/plants.toml."""

from __future__ import annotations

import argparse
import pathlib
import sys
import tomllib


ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "plants.toml"
TARGET = ROOT / "content" / "generated" / "plant_data.typ"


def q(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def c(text: str) -> str:
    return f'[#text("{q(text)}")]'


def load_plants() -> list[dict]:
    with SOURCE.open("rb") as f:
        parsed = tomllib.load(f)
    return parsed["plants"]


def build_emitter_rows(plants: list[dict]) -> list[tuple[str, str, str]]:
    rows = []
    for plant in plants:
        if plant.get("irrigation") != "drip":
            continue
        if "emitter_display" not in plant or "emitter_note" not in plant:
            raise KeyError(
                "Missing emitter_display/emitter_note for drip plant: "
                f'{plant.get("file", plant["name"])}'
            )
        emitters = plant["emitter_display"]
        note = plant["emitter_note"]
        rows.append((plant["name"], emitters, note))
    return rows


def build_fertilizer_rows(plants: list[dict]) -> list[tuple[str, str]]:
    rows = []
    for plant in plants:
        if "fertilizer_program" not in plant:
            raise KeyError(
                "Missing fertilizer_program for plant: "
                f'{plant.get("file", plant["name"])}'
            )
        rows.append((plant["name"], plant["fertilizer_program"]))
    return rows


def build_lifespan_rows(plants: list[dict]) -> list[tuple[str, str]]:
    rows = []
    for plant in plants:
        if "lifespan" not in plant:
            raise KeyError(
                "Missing lifespan for plant: "
                f'{plant.get("file", plant["name"])}'
            )
        rows.append((plant["name"], plant["lifespan"]))
    return rows


def build_risk_rows(plants: list[dict]) -> list[tuple[str, str, str]]:
    rows = []
    for plant in plants:
        if "maintenance_tier" not in plant:
            raise KeyError(
                "Missing maintenance_tier for plant: "
                f'{plant.get("file", plant["name"])}'
            )
        if "primary_failure_mode" not in plant:
            raise KeyError(
                "Missing primary_failure_mode for plant: "
                f'{plant.get("file", plant["name"])}'
            )
        rows.append((plant["name"], plant["maintenance_tier"], plant["primary_failure_mode"]))
    return rows


def build_profile_rows(plants: list[dict]) -> list[tuple[str, str, str, str, str]]:
    rows = []
    for plant in plants:
        if "file" not in plant:
            raise KeyError("Missing file key for plant profile lookup")
        if (
            "established" not in plant
            or "lifespan" not in plant
            or "maintenance_tier" not in plant
            or "primary_failure_mode" not in plant
        ):
            raise KeyError(
                "Missing profile field(s) for plant: "
                f'{plant.get("file", plant["name"])}'
            )
        rows.append(
            (
                plant["file"],
                str(plant["established"]),
                plant["lifespan"],
                str(plant["maintenance_tier"]).capitalize(),
                plant["primary_failure_mode"],
            )
        )
    return rows


def render_typst(
    emitter_rows: list[tuple[str, str, str]],
    fertilizer_rows: list[tuple[str, str]],
    lifespan_rows: list[tuple[str, str]],
    risk_rows: list[tuple[str, str, str]],
    profile_rows: list[tuple[str, str, str, str, str]],
) -> str:
    lines = []
    lines.append("// AUTO-GENERATED by scripts/generate_plant_data_typ.py")
    lines.append("// Source: data/plants.toml")
    lines.append("// Do not edit manually. Run: make generate")
    lines.append("")
    lines.append('#import "../../template.typ": *')
    lines.append("")
    lines.append("#let emitter-config-table = table(")
    lines.append("  columns: (8fr, 3fr, 17fr),")
    lines.append("  fill: tbl-fill,")
    lines.append("  stroke: tbl-stroke,")
    lines.append("  align: (left, left, left),")
    lines.append("")
    lines.append("  tbl-header-text[Plant],")
    lines.append("  tbl-header-text[Emitters],")
    lines.append("  tbl-header-text[Notes],")
    lines.append("")
    for name, emitters, note in emitter_rows:
        lines.append(f"  {c(name)}, {c(emitters)}, {c(note)},")
    lines.append(")")
    lines.append("")
    lines.append("#let fertilizer-program-table = table(")
    lines.append("  columns: (1.2fr, 3.1fr),")
    lines.append("  fill: tbl-fill,")
    lines.append("  stroke: tbl-stroke,")
    lines.append("  align: (left, left),")
    lines.append("")
    lines.append("  tbl-header-text[Plant],")
    lines.append("  tbl-header-text[Fertilizer Program],")
    lines.append("")
    for name, program in fertilizer_rows:
        lines.append(f"  {c(name)}, {c(program)},")
    lines.append(")")
    lines.append("")
    lines.append("#let plant-lifespan-table = table(")
    lines.append("  columns: (1.9fr, 1.4fr),")
    lines.append("  fill: tbl-fill,")
    lines.append("  stroke: tbl-stroke,")
    lines.append("  align: (left, left),")
    lines.append("")
    lines.append("  tbl-header-text[Plant],")
    lines.append("  tbl-header-text[Typical Lifespan],")
    lines.append("")
    for name, lifespan in lifespan_rows:
        lines.append(f"  {c(name)}, {c(lifespan)},")
    lines.append(")")
    lines.append("")
    lines.append("#let plant-risk-table = table(")
    lines.append("  columns: (1.6fr, 0.8fr, 2.6fr),")
    lines.append("  fill: tbl-fill,")
    lines.append("  stroke: tbl-stroke,")
    lines.append("  align: (left, left, left),")
    lines.append("")
    lines.append("  tbl-header-text[Plant],")
    lines.append("  tbl-header-text[Tier],")
    lines.append("  tbl-header-text[Primary Failure Mode],")
    lines.append("")
    for name, tier, mode in risk_rows:
        lines.append(f"  {c(name)}, {c(tier)}, {c(mode)},")
    lines.append(")")
    lines.append("")
    lines.append("#let plant-profile-map = (")
    for file_key, established, lifespan, tier, mode in profile_rows:
        lines.append(
            f'  "{q(file_key)}": ("{q(established)}", "{q(lifespan)}", "{q(tier)}", "{q(mode)}"),'
        )
    lines.append(")")
    lines.append("")
    lines.append("#let plant-established(file-key) = {")
    lines.append("  let (established, _, _, _) = plant-profile-map.at(file-key)")
    lines.append("  established")
    lines.append("}")
    lines.append("")
    lines.append("#let plant-lifespan(file-key) = {")
    lines.append("  let (_, lifespan, _, _) = plant-profile-map.at(file-key)")
    lines.append("  lifespan")
    lines.append("}")
    lines.append("")
    lines.append("#let plant-tier(file-key) = {")
    lines.append("  let (_, _, tier, _) = plant-profile-map.at(file-key)")
    lines.append("  tier")
    lines.append("}")
    lines.append("")
    lines.append("#let plant-failure(file-key) = {")
    lines.append("  let (_, _, _, mode) = plant-profile-map.at(file-key)")
    lines.append("  mode")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated file is out of date.")
    args = parser.parse_args()

    plants = load_plants()
    emitter_rows = build_emitter_rows(plants)
    fertilizer_rows = build_fertilizer_rows(plants)
    lifespan_rows = build_lifespan_rows(plants)
    risk_rows = build_risk_rows(plants)
    profile_rows = build_profile_rows(plants)
    rendered = render_typst(
        emitter_rows,
        fertilizer_rows,
        lifespan_rows,
        risk_rows,
        profile_rows,
    )

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    if args.check:
        if not TARGET.exists():
            print(f"{TARGET} is missing; run make generate", file=sys.stderr)
            return 1
        existing = TARGET.read_text(encoding="utf-8")
        if existing != rendered:
            print(f"{TARGET} is stale; run make generate", file=sys.stderr)
            return 1
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    print(f"Wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
