#!/usr/bin/env python3
"""Generate Typst reference include from non-plant TOML data files."""

from __future__ import annotations

import argparse
import pathlib
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOIL = ROOT / "data" / "soil.toml"
LAWN = ROOT / "data" / "lawn_program.toml"
INVENTORY = ROOT / "data" / "inventory.toml"
TARGET = ROOT / "content" / "generated" / "reference_data.typ"


def q(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def c(text: str) -> str:
    return f'[#text("{q(text)}")]'


def load_toml(path: pathlib.Path) -> dict:
    with path.open("rb") as f:
        return tomllib.load(f)


def status_expr(severity: str, text: str) -> str:
    if severity == "warn":
        return f'[#text(fill: status-warn, weight: "bold", "{q(text)}")]'
    if severity == "high":
        return f'[#text(fill: status-high, "{q(text)}")]'
    if severity == "ok":
        return f'[#text(fill: status-ok, "{q(text)}")]'
    return c(text)


def render() -> str:
    soil = load_toml(SOIL)
    lawn = load_toml(LAWN)
    inventory = load_toml(INVENTORY)

    rows = soil["rows"]
    if not rows:
        raise ValueError("data/soil.toml rows is empty")

    preen = next((i for i in inventory["items"] if i.get("id") == "preen_bed_preemergent"), None)
    if preen is None:
        raise ValueError("data/inventory.toml missing preen_bed_preemergent")

    lp = lawn["lawn_program"]
    n_range = f'{lp["annual_n_min"]}–{lp["annual_n_max"]}'

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by scripts/generate_reference_data_typ.py")
    lines.append("// Sources: data/soil.toml, data/lawn_program.toml, data/inventory.toml")
    lines.append("// Do not edit manually. Run: make generate")
    lines.append("")
    lines.append('#import "../../template.typ": *')
    lines.append("")
    lines.append(f'#let soil-ph = "{soil["soil"]["ph"]}"')
    lines.append(f'#let lawn-size-sqft = {lp["lawn_sqft"]}')
    lines.append(f'#let lawn-n-range-display = "{n_range}"')
    lines.append(f'#let preen-inventory-qty = {preen["quantity"]}')
    lines.append(f'#let preen-inventory-unit = "{q(preen["unit"])}"')
    lines.append(f'#let preen-status = "{q(preen["status"])}"')
    lines.append(f'#let preen-season-lock = "{q(preen["season_lock"])}"')
    lines.append(f'#let preen-scope = "{q(preen["scope"])}"')
    lines.append("")
    lines.append("#let soil-profile-table = table(")
    lines.append("  columns: (1fr, 1fr, 4.5fr),")
    lines.append("  fill: tbl-fill,")
    lines.append("  stroke: tbl-stroke,")
    lines.append("  align: (left, left, left),")
    lines.append("")
    lines.append("  tbl-header-text[Parameter],")
    lines.append("  tbl-header-text[Status],")
    lines.append("  tbl-header-text[Management],")
    lines.append("")

    for row in rows:
        sev = row.get("severity", "plain")
        st = row.get("status_text", "")
        lines.append(f'  {c(row["parameter"])},')
        lines.append(f"  {status_expr(sev, st)},")
        lines.append(f'  {c(row["management"])},')

    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated file is out of date.")
    args = parser.parse_args()

    rendered = render()
    TARGET.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        if not TARGET.exists():
            print(f"{TARGET} is missing; run make generate", file=sys.stderr)
            return 1
        existing = TARGET.read_text(encoding="utf-8")
        if existing != rendered:
            print(f"{TARGET} is stale; run make generate", file=sys.stderr)
            return 1
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    print(f"Wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
